Задачи к занятию 3
js-tasks-ru/jsbasic-20240321_dmitry-koryanov pull request #3
Opened 2024-04-01 16:55 UTC by dmitrykoryanov

2024-04-01 16:56 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-01 18:59 UTC, SinimaWath requested changes

2024-04-01 18:59 UTC, SinimaWath commented on 3-module/3-task/index.js
> +      .reduce((result, current) => result + current, '');
вместо `reduce` в конце давай заиспользуем более подходящий метод: `.join('')`

2024-04-01 18:59 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  resultString = resultString.slice(0, resultString.length - 1);
Чтобы не делать костылей с `+ '\n'`, давай заиспользуем метод: `join('\n')`

2024-04-13 06:46 UTC, dmitrykoryanov commented on 3-module/3-task/index.js
> +      .reduce((result, current) => result + current, '');
Done.

2024-04-13 06:50 UTC, dmitrykoryanov commented on 3-module/4-task/index.js
> +  resultString = resultString.slice(0, resultString.length - 1);
Да, так гораздо лучше, теперь в одну строчку. Done.

2024-04-13 07:43 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-13 09:03 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-04-13 22:45 UTC, SinimaWath approved these changes
все круто!

2024-04-13 22:47 UTC, merged